/**
 * Lista de nichos de mercado disponíveis para seleção de candidatos e vagas.
 * Cada item contém:
 * - label: texto exibido para o usuário
 * - value: valor interno salvo no banco de dados
 *
 * Nichos comentados estão planejados para versões futuras do app.
 */
export const nichos = [
  { label: 'Tecnologia da Informação e Comunicação', value: 'tecnologia' },
  { label: 'Logística e Supply Chain', value: 'logistica' },
  { label: 'Segurança Privada e Vigilância', value: 'seguranca' },
  { label: 'Comércio e Varejo', value: 'varejo' },

  /*
  { label: 'Facilities e Serviços Gerais', value: 'facilities' },
  { label: 'Indústria e Manufatura', value: 'industria' },
  { label: 'Saúde e Assistência Social', value: 'saude' },
  { label: 'Construção Civil e Obras', value: 'construcao' },
  { label: 'Agronegócio e Agropecuária', value: 'agronegocio' },
  { label: 'Vendas e Comercial', value: 'vendas' },
  { label: 'Educação e Treinamento', value: 'educacao' },
  { label: 'Financeiro e Bancário', value: 'financeiro' },
  { label: 'Hotelaria, Turismo e Hospitalidade', value: 'turismo' },
  { label: 'Energia, Mineração e Utilidades', value: 'energia' },
  { label: 'Alimentação e Bebidas', value: 'alimentacao' },
  { label: 'Administração e Gestão', value: 'administracao' },
  { label: 'Recursos Humanos', value: 'rh' },
  { label: 'Marketing e Publicidade', value: 'marketing' },
  { label: 'Jurídico e Direito', value: 'juridico' },
  { label: 'Contabilidade e Finanças', value: 'contabilidade' },
  { label: 'Engenharia (Geral)', value: 'engenharia' },
  { label: 'Produção Industrial', value: 'producao' },
  { label: 'Qualidade e Controle', value: 'qualidade' },
  { label: 'Manutenção e Suporte Técnico', value: 'manutencao' },
  { label: 'Atendimento ao Cliente', value: 'atendimento' },
  { label: 'Call Center e Telemarketing', value: 'callcenter' },
  { label: 'E-commerce e Mercado Digital', value: 'ecommerce' },
  { label: 'Telecomunicações', value: 'telecomunicacoes' },
  { label: 'Farmacêutico e Drogarias', value: 'farmaceutico' },
  { label: 'Beleza, Estética e Bem-Estar', value: 'beleza' },
  { label: 'Eventos e Entretenimento', value: 'eventos' },
  { label: 'Mídia, Comunicação e Jornalismo', value: 'midia' },
  { label: 'Design e Criativo', value: 'design' },
  { label: 'Arquitetura e Urbanismo', value: 'arquitetura' },
  { label: 'Imobiliário e Corretagem', value: 'imobiliario' },
  { label: 'Seguros e Previdência', value: 'seguros' },
  { label: 'Consultoria Empresarial', value: 'consultoria' },
  { label: 'Auditoria e Compliance', value: 'auditoria' },
  { label: 'Petróleo, Gás e Derivados', value: 'petroleo' },
  { label: 'Automotivo e Peças', value: 'automotivo' },
  { label: 'Têxtil e Confecção', value: 'textil' },
  { label: 'Química e Petroquímica', value: 'quimica' },
  { label: 'Meio Ambiente e Sustentabilidade', value: 'meioambiente' },
  { label: 'Pesquisa e Desenvolvimento (P&D)', value: 'pesquisa' },
  { label: 'Biotecnologia e Ciências da Vida', value: 'biotecnologia' },
  { label: 'Esportes, Fitness e Lazer', value: 'esportes' },
  { label: 'Transporte Rodoviário', value: 'transporte_rodoviario' },
  { label: 'Transporte Aéreo', value: 'transporte_aereo' },
  { label: 'Portos e Logística Portuária', value: 'portos' },
  { label: 'Mineração', value: 'mineracao' },
  { label: 'Eletricidade e Gás', value: 'eletricidade' },
  { label: 'Água, Saneamento e Resíduos', value: 'saneamento' },
  { label: 'Cultura, Artes e Recreação', value: 'cultura' },
  { label: 'Veterinária e Zootecnia', value: 'veterinaria' },
  { label: 'Metalurgia e Siderurgia', value: 'metalurgia' },
  { label: 'Papel e Celulose', value: 'papel_celulose' },
  { label: 'Calçados e Couro', value: 'calcados' },
  { label: 'Mobiliário', value: 'mobiliario' },
  { label: 'Plásticos e Borracha', value: 'plasticos' },
  { label: 'Eletroeletrônicos', value: 'eletroeletronicos' },
  { label: 'Administração Pública e Setor Público', value: 'administracao_publica' },
  */
];
